server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name localhost 127.0.0.1;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/kea-test/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/kea-test/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/kea-test/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location /dhcp4 {
        proxy_pass http://127.0.0.1:8080/;
    }
    location /dhcp6 {
        proxy_pass http://127.0.0.1:8081/;
    }
}
