name: "simple-build-test"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile*"
      - "Makefile"
      - "build.sh"
      - "entrypoint.sh"
      - ".github/scripts/**"
      - ".github/workflows/simple_build_test.yml"

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Build the amd64 version of the Debian image
        run: make all

      - name: Check for new/changed hook libraries
        run: docker run kea-hooks:local ls -1 /hooks | diff .github/kea_hook_libraries.list -

      - name: Test DHCPv4 offer and Kea logs
        timeout-minutes: 5
        run: bash .github/scripts/test_dhcp4.sh kea-dhcp4:local

  docker_buildx_alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Build the amd64 version of the Alpine image
        run: make all-alpine

      - name: Check for new/changed hook libraries
        run: docker run kea-hooks:local-alpine ls -1 /hooks | diff .github/kea_hook_libraries.list -

      - name: Test DHCPv4 offer and Kea logs
        timeout-minutes: 5
        run: bash .github/scripts/test_dhcp4.sh kea-dhcp4:local-alpine
